import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const THEME_DIR = path.resolve(__dirname, "..", "fixtures", "theme");
const OUTPUT_FILE = path.resolve(__dirname, "..", "fixtures", "theme-bundle.ts");

function findLiquidFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findLiquidFiles(full));
    } else if (entry.name.endsWith(".liquid")) {
      results.push(full);
    }
  }
  return results;
}

function main() {
  if (!fs.existsSync(THEME_DIR)) {
    console.error(`Error: ${THEME_DIR} does not exist.`);
    console.error("Run scripts/download-themes.ts first to populate theme fixtures.");
    process.exit(1);
  }

  const files = findLiquidFiles(THEME_DIR);

  if (files.length === 0) {
    console.error(`Error: No .liquid files found in ${THEME_DIR}.`);
    console.error("Run scripts/download-themes.ts first to populate theme fixtures.");
    process.exit(1);
  }

  files.sort();

  const entries = files.map((file) => {
    const relPath = path.relative(THEME_DIR, file);
    const source = fs.readFileSync(file, "utf-8");
    return { path: relPath, source };
  });

  const totalBytes = entries.reduce((sum, e) => sum + Buffer.byteLength(e.source, "utf-8"), 0);

  const lines = [
    "// Auto-generated by scripts/generate-theme-bundle.ts — do not edit",
    "export const THEME_FILES: Array<{ path: string; source: string }> = [",
  ];

  for (const entry of entries) {
    lines.push("  {");
    lines.push(`    path: ${JSON.stringify(entry.path)},`);
    lines.push(`    source: ${JSON.stringify(entry.source)},`);
    lines.push("  },");
  }

  lines.push("];");
  lines.push("");

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"));

  console.log(
    `Bundled ${entries.length} files (${(totalBytes / 1024).toFixed(1)} KB) into ${OUTPUT_FILE}`,
  );
}

main();
