import { LiquidVariableLookup } from '@shopify/liquid-html-parser';
import { LiquidCheckDefinition, Severity, SourceCodeType } from '../../types';
import { isBlock } from '../../to-schema';
import { getSchema } from '../../to-schema';
import { nodeAtPath } from '../../json';
import { reportWarning } from '../../utils';

const SHOPIFY_ATTRIBUTES_KEY = 'shopify_attributes';
const BLOCK_OBJECT = 'block';

/**
 * When a block schema declares `"tag": null`, the block has no wrapping element
 * generated by Shopify. To stay registered with the theme editor, the markup
 * the block renders MUST contain `{{ block.shopify_attributes }}` somewhere on
 * its outermost element. Forgetting this leaves the block unrecognised in the
 * preview and produces orphaned markup when merchants reorder blocks.
 *
 * @see https://shopify.dev/docs/storefronts/themes/architecture/blocks/theme-blocks/schema#tag
 *
 * Phase 1 (this implementation, per #867): only the current file is checked.
 * Cases where the block's markup is delegated to a rendered snippet, or where
 * `block.shopify_attributes` ends up rendered multiple times, are out of scope.
 */
export const BlockMissingShopifyAttributes: LiquidCheckDefinition = {
  meta: {
    code: 'BlockMissingShopifyAttributes',
    name: 'Block missing block.shopify_attributes',
    docs: {
      description:
        'Warns when a block file with `"tag": null` in its schema does not render `{{ block.shopify_attributes }}` on its outermost element.',
      recommended: true,
      url: 'https://shopify.dev/docs/storefronts/themes/tools/theme-check/checks/block-missing-shopify-attributes',
    },
    type: SourceCodeType.LiquidHtml,
    severity: Severity.WARNING,
    schema: {},
    targets: [],
  },

  create(context) {
    // Skip non-block files entirely. Section files have their own wrapping
    // semantics and do not require `block.shopify_attributes`.
    if (!isBlock(context.file.uri)) return {};

    let hasShopifyAttributes = false;
    let schemaOffset: number | null = null;

    return {
      async LiquidRawTag(node) {
        if (node.name !== 'schema' || node.body.kind !== 'json') return;
        // Captured here so we can translate JSON-AST positions to file
        // positions inside `onCodePathEnd`.
        schemaOffset = node.blockStartPosition.end;
      },

      async VariableLookup(node: LiquidVariableLookup) {
        if (hasShopifyAttributes) return;
        if (node.name !== BLOCK_OBJECT) return;

        // `block.shopify_attributes` shows up as a VariableLookup with
        // `name === 'block'` and a single string lookup of
        // `'shopify_attributes'`. Bracket access (`block['shopify_attributes']`)
        // is also accepted because liquid-html-parser normalises both forms
        // to a `String` lookup with the same `value`.
        const matches = node.lookups.some(
          (lookup) => lookup.type === 'String' && lookup.value === SHOPIFY_ATTRIBUTES_KEY,
        );
        if (matches) {
          hasShopifyAttributes = true;
        }
      },

      async onCodePathEnd() {
        if (hasShopifyAttributes) return;
        if (schemaOffset === null) return;

        const schema = await getSchema(context);
        if (!schema) return;

        const { validSchema, ast } = schema;
        if (!validSchema || validSchema instanceof Error) return;
        if (!ast || ast instanceof Error) return;

        // The schema field is `tag` and we only flag the explicit `null` case.
        // Missing `tag` (i.e. the schema-default behaviour where Shopify wraps
        // the block in a `<div>`) does NOT require `block.shopify_attributes`,
        // because Shopify's wrapper element receives the attributes itself.
        if (!('tag' in validSchema) || validSchema.tag !== null) return;

        const tagNode = nodeAtPath(ast, ['tag']);
        if (!tagNode) return;

        reportWarning(
          `Blocks with \`"tag": null\` must render \`{{ block.shopify_attributes }}\` on their outermost element so the theme editor can recognise the block.`,
          schemaOffset,
          tagNode,
          context,
        );
      },
    };
  },
};
